export type Locale = 'ca' | 'es' | 'en';

export type StoryTranslation = {
  title: string;
  body: string;
};

export type UserRole = 'user' | 'admin';

export type UserAccount = {
  id: string;
  email: string;
  name: string;
  passwordSalt: string;
  passwordHash: string;
  profileImageUrl: string;
  favoriteStorypointIds: string[];
  role: UserRole;
  createdAt: string;
  updatedAt: string;
  recoveryCode?: string;
  recoveryCodeExpiresAt?: number;
};

export type Storypoint = {
  id: string;
  slug: string;
  locationName: string;
  lat: number;
  lng: number;
  originalLocale: Locale;
  submittedByUserId?: string;
  submittedByUserName?: string;
  submittedByEmail?: string;
  submittedByProfileImageUrl?: string;
  translations: Record<Locale, StoryTranslation>;
};

export type StorypointRequest = {
  id: string;
  title: string;
  body: string;
  email: string;
  submittedByUserId?: string;
  submittedByUserName?: string;
  submittedByProfileImageUrl?: string;
  locale: Locale;
  lat: number;
  lng: number;
  status: 'pending' | 'approved' | 'rejected';
  createdAt: string;
  reviewedAt?: string;
  reviewerNote?: string;
};

export type Messages = {
  appName: string;
  subtitle: string;
  mapTitle: string;
  mapCopy: string;
  requestStorypoint: string;
  cancelRequest: string;
  openStory: string;
  close: string;
  play: string;
  pause: string;
  tts: string;
  largerText: string;
  smallerText: string;
  useLocation: string;
  locationDenied: string;
  requestSubmitted: string;
  requestFormTitle: string;
  requestFormEmail: string;
  requestFormStory: string;
  submitRequest: string;
  password: string;
  signInToContinue: string;
  requestFollowUp: string;
  accountTitle: string;
  signIn: string;
  signUp: string;
  signOut: string;
  register: string;
  confirmPassword: string;
  name: string;
  profileImage: string;
  saveAccount: string;
  currentPassword: string;
  newPassword: string;
  invalidCredentials: string;
  emailAlreadyInUse: string;
  accountSettings: string;
  myRequests: string;
  favorites: string;
  myStorypoints: string;
  noRequests: string;
  noPendingRequests: string;
  noFavorites: string;
  noStorypoints: string;
  requestOwner: string;
  viewProfile: string;
  favoriteStorypoint: string;
  unfavoriteStorypoint: string;
  loginToFavorite: string;
  loginToRequest: string;
  signInRequired: string;
  profileTitle: string;
  profileStorypoints: string;
  profileSubtitle: string;
  adminStorypoints: string;
  deleteStorypoint: string;
  delete: string;
  accepted: string;
  rejected: string;
  requestAccepted: string;
  requestRejected: string;
  donationsTitle: string;
  whoWeAreTitle: string;
  adminTitle: string;
  adminLogin: string;
  login: string;
  approve: string;
  reject: string;
  pendingRequests: string;
  forgotPassword: string;
  recoverPassword: string;
  sendRecoveryCode: string;
  recoveryEmailSent: string;
  invalidRecoveryCode: string;
  passwordResetSuccess: string;
  resetPassword: string;
  recoveryCode: string;
  deleteConfirm: string;
  deleteRequest: string;
  deleteFavorite: string;
  deleteStorypointItem: string;
 };
